### ISSUE TITLE
Error in extras_tooltips.js on user profile page

### ISSUE THREAD

**Issue by tomillie** [tomillie/CsfdExtensions#27]
In a console, there is this error:

```
Error in response to storage.get: TypeError: $(...).hoverIntent is not a function
    at Object.callback (chrome-extension://gjifpdjcmgbhpcefhkmejpmaahkdjlii/js/extras_tooltips.js:89:36)
    at HTMLDocument.<anonymous> (chrome-extension://gjifpdjcmgbhpcefhkmejpmaahkdjlii/js/extras_tooltips.js:8:30)
    at f.Callbacks.n (chrome-extension://gjifpdjcmgbhpcefhkmejpmaahkdjlii/js/jquery.js:2:14784)
    at Object.f.Callbacks.o.fireWith (chrome-extension://gjifpdjcmgbhpcefhkmejpmaahkdjlii/js/jquery.js:2:15553)
    at e.extend.ready (chrome-extension://gjifpdjcmgbhpcefhkmejpmaahkdjlii/js/jquery.js:2:9773)
```

**Comment by tomillie** [comment]
Fixed in v6.0.
